--- 
abstract: flexible dispatch
author: 
  - Shawn M Moore, C<< <sartak at bestpractical.com> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Path-Dispatcher
no_index: 
  directory: 
    - inc
    - t
requires: 
  Moose: 0
  MooseX::AttributeHelpers: 0
  Sub::Exporter: 0
version: 0.03
